# Uncomment the next line to define a global platform for your project
# platform :ios, '10.3'

target 'Time Transac' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Time Transac
  pod ‘lottie-ios’
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Pastel'
  pod ‘IBAnimatable’
  pod 'Material', '~> 2.0'
  pod 'Alamofire'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Mapbox-iOS-SDK', '~> 3.7'
  pod 'PopupDialog', '~> 0.6'
  pod 'Stripe'
  pod 'SHSearchBar'
  pod 'Kingfisher', '~> 4.0'
  pod 'RevealingSplashView'
  pod 'Firebase/Storage'
  pod 'CHIPageControl/Fresno'
  pod 'MapboxNavigation'
  pod 'NotificationBannerSwift'
  
  target 'Time TransacTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Time TransacUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
